import React from 'react';
import { Link } from 'react-router-dom';


const HomeBody = () => {
    return (
        <div>
            <h1 className='text-center m-4 text-info' >Welcome Message</h1>
            <p className='p-3'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Et ex quasi incidunt debitis, aperiam est necessitatibus repudiandae. Ad officia modi magnam tenetur neque itaque necessitatibus ut doloremque provident voluptatibus sunt deleniti molestiae sed, odio aut accusantium soluta, non at ea. Dolores, voluptatibus? Corporis iusto sunt odio architecto vero porro quibusdam ut temporibus explicabo adipisci sit, culpa pariatur voluptatum aut consectetur dignissimos at tempora in cupiditate laboriosam dolores eaque maiores. Rerum sit voluptatem placeat, cum ducimus tempore suscipit blanditiis nemo quia dolorum aut ad, reprehenderit perferendis animi possimus fuga fugit nesciunt sapiente saepe perspiciatis, laborum ipsa? Minima suscipit obcaecati illo, officia repellendus asperiores ad beatae molestias totam repudiandae, modi sequi vel? Minus iure ratione consectetur ducimus autem odio sapiente possimus mollitia cupiditate accusamus est, aliquam error dolorem saepe laborum sit molestias. Natus laborum exercitationem quis accusamus earum, repudiandae aspernatur a nihil dolorum voluptates voluptatem quam corrupti minima mollitia? Ullam totam soluta obcaecati similique officia molestias consectetur delectus atque ratione neque accusamus facilis quasi amet quibusdam, ut iste. Iste facilis nostrum maxime! Exercitationem necessitatibus voluptatibus harum non vero quidem magnam repellendus accusamus quae, beatae expedita consectetur facere voluptate rerum? Nulla, eaque, ratione impedit eius dolorum omnis pariatur id quis ut libero ipsam nostrum veritatis vero voluptatem tempore illo voluptas voluptatibus culpa distinctio. Voluptas, unde alias laboriosam facilis suscipit dicta iure ex consequuntur beatae animi ipsa qui? Nemo laborum pariatur consectetur ex? Sunt obcaecati voluptatibus aspernatur dolores perferendis deserunt consequatur ab similique aliquam eligendi reprehenderit eius, architecto maiores rem cumque, soluta aperiam quaerat.</p>
            <p className='mb-4 p-3'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga, recusandae alias voluptatem ea inventore mollitia perspiciatis vel sed, doloribus quas reprehenderit vitae molestias beatae facilis iusto nulla, consequatur voluptatum quisquam? Temporibus reiciendis sed, aspernatur nulla nesciunt ex natus assumenda quas veritatis. Illum accusamus totam, maiores a quis neque aliquid nesciunt fugiat odit velit eligendi voluptates, aperiam doloremque nostrum. Dolorum mollitia deserunt qui cupiditate non? Vero debitis eos error repellendus, impedit, pariatur mollitia numquam sed quibusdam blanditiis dolorem laudantium obcaecati optio minus illum repudiandae fugiat. Porro quia velit quaerat laudantium praesentium, magni repellat facilis harum necessitatibus hic totam alias culpa excepturi tempora nulla tenetur nam quis iure modi laborum? Nam, repudiandae recusandae! Veritatis dolorem sunt ea minima nam ullam deleniti similique molestias iusto explicabo voluptas quo quisquam cupiditate saepe odio, ab, aliquam animi numquam beatae voluptatum, omnis quos. Voluptas, temporibus atque quis adipisci exercitationem aperiam ipsam magni iusto eius quaerat ab. Ad maxime eum quod atque vel deserunt quaerat culpa, molestias rem odio voluptatibus consequuntur aliquid nostrum sapiente repellendus doloribus? Distinctio ex provident ducimus dolor voluptatibus! Quam obcaecati vitae est nesciunt laboriosam assumenda suscipit eos culpa officiis reprehenderit, minima, totam velit temporibus ipsum consectetur recusandae veniam quibusdam cumque reiciendis veritatis perspiciatis repellendus fugit, sunt porro! Consectetur, soluta fugiat eveniet ullam aut officiis molestiae mollitia dignissimos, quas similique temporibus ad praesentium perspiciatis. Qui alias doloribus temporibus maxime, quos repellendus quidem quaerat cumque quae ipsam accusantium culpa ipsum veniam magnam. Laborum, temporibus quibusdam labore, totam libero cupiditate alias tempore vel, reiciendis est earum!</p>
            <Link to='/resumeform' >
                <div class="d-grid gap-2 col-6 mx-auto mt-4">
                    <button class="btn btn-outline-success mb-4" type="button">Create Resume</button>
                </div>
            </Link>
        </div>
    )
}

export default HomeBody